In [1]:
import pandas as pd
import numpy as np

In [5]:
# create series
Series1 = pd.Series([1,2,3,4])
Series1

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
# series with custom index labels
Series1 = pd.Series([1,2,3,4] , index = ["first", "second", "third", "fourth"])
Series1

first     1
second    2
third     3
fourth    4
dtype: int64

In [9]:
Series2 = pd.Series([5,6,7,8] , index = ["first", "fifth", "sixth", "fourth"])
Series2

first     5
fifth     6
sixth     7
fourth    8
dtype: int64

In [10]:
# Adding 2 series : 2 labels with same name will get add ..if labels are not same then it will give NaN
print(Series1  + Series2)

fifth      NaN
first      6.0
fourth    12.0
second     NaN
sixth      NaN
third      NaN
dtype: float64

In [11]:
## DataFrame: Concatinating 2 series

column_wse_concat_df = pd.concat([Series1, Series2], axis = 1)
column_wse_concat_df

          0    1
first   1.0  5.0
second  2.0  NaN
third   3.0  NaN
fourth  4.0  8.0
fifth   NaN  6.0
sixth   NaN  7.0

In [12]:
row_wse_concat = pd.concat([Series1, Series2], axis=0)
row_wse_concat

first     1
second    2
third     3
fourth    4
first     5
fifth     6
sixth     7
fourth    8
dtype: int64

In [14]:
## create dataframe using numpy array
df1 = pd.DataFrame(np.random.rand(5,4))
df1

          0         1         2         3
0  0.599007  0.176173  0.641139  0.190404
1  0.863547  0.384936  0.569351  0.564776
2  0.357348  0.143491  0.465712  0.328841
3  0.455256  0.255176  0.451067  0.769496
4  0.609813  0.845960  0.008094  0.464688

In [19]:
df1 = pd.DataFrame(np.random.rand(5,4), index = ["index1","index2","index3","index4","index5"], 
                   columns = ["col1","col2","col3","col4"])
df1

            col1      col2      col3      col4
index1  0.732208  0.355399  0.195054  0.835518
index2  0.577719  0.453597  0.727921  0.864443
index3  0.883460  0.292515  0.031291  0.652371
index4  0.707476  0.071373  0.105123  0.994128
index5  0.553048  0.559555  0.316286  0.041482

In [23]:
## Access columns

print(df1["col1"])                      # single column

print("")

print(df1[["col1", "col2"]])            # Multiple columns

index1    0.732208
index2    0.577719
index3    0.883460
index4    0.707476
index5    0.553048
Name: col1, dtype: float64

            col1      col2
index1  0.732208  0.355399
index2  0.577719  0.453597
index3  0.883460  0.292515
index4  0.707476  0.071373
index5  0.553048  0.559555

In [28]:
## Acces rows by indexname 

print(df1.loc["index3"])             ## using loc i.e. using index name

print("")

print(df1.iloc[2])                  ## using iloc  i.e using index number

col1    0.883460
col2    0.292515
col3    0.031291
col4    0.652371
Name: index3, dtype: float64

col1    0.883460
col2    0.292515
col3    0.031291
col4    0.652371
Name: index3, dtype: float64

In [29]:
df1

            col1      col2      col3      col4
index1  0.732208  0.355399  0.195054  0.835518
index2  0.577719  0.453597  0.727921  0.864443
index3  0.883460  0.292515  0.031291  0.652371
index4  0.707476  0.071373  0.105123  0.994128
index5  0.553048  0.559555  0.316286  0.041482

In [36]:
## Access row : 0,2,3 and Access columns : 1,3

df1.iloc[[0,2, 3], [1,3]]

            col2      col4
index1  0.355399  0.835518
index3  0.292515  0.652371
index4  0.071373  0.994128

In [37]:
## We can do logical indexing in dataframe.

df1 < 0.2

         col1   col2   col3   col4
index1  False  False   True  False
index2  False  False  False  False
index3  False  False   True  False
index4  False   True   True  False
index5  False  False  False   True

In [39]:
## when we subset dataframe , it gives NaN where value is False.

df1[df1 < 0.2]

        col1      col2      col3      col4
index1   NaN       NaN  0.195054       NaN
index2   NaN       NaN       NaN       NaN
index3   NaN       NaN  0.031291       NaN
index4   NaN  0.071373  0.105123       NaN
index5   NaN       NaN       NaN  0.041482

In [42]:
## Add column tp dataframe
## It will autocheck ,, if colname is already exist then it dont create that column

df1["col5"] = np.random.randn(5,1)
df1

            col1      col2      col3      col4      col5
index1  0.732208  0.355399  0.195054  0.835518  0.491631
index2  0.577719  0.453597  0.727921  0.864443 -0.640731
index3  0.883460  0.292515  0.031291  0.652371  0.295773
index4  0.707476  0.071373  0.105123  0.994128  1.080614
index5  0.553048  0.559555  0.316286  0.041482  0.844003

In [43]:
## to reset index name from dataframe
df1.reset_index()

    index      col1      col2      col3      col4      col5
0  index1  0.732208  0.355399  0.195054  0.835518  0.491631
1  index2  0.577719  0.453597  0.727921  0.864443 -0.640731
2  index3  0.883460  0.292515  0.031291  0.652371  0.295773
3  index4  0.707476  0.071373  0.105123  0.994128  1.080614
4  index5  0.553048  0.559555  0.316286  0.041482  0.844003

In [45]:
## Above only return with default index , but if we want to make this chgange permanent .. we can use inplace = True 
df1

# df1.reset_index(inplace = True)

            col1      col2      col3      col4      col5
index1  0.732208  0.355399  0.195054  0.835518  0.491631
index2  0.577719  0.453597  0.727921  0.864443 -0.640731
index3  0.883460  0.292515  0.031291  0.652371  0.295773
index4  0.707476  0.071373  0.105123  0.994128  1.080614
index5  0.553048  0.559555  0.316286  0.041482  0.844003

In [53]:
## we can assign new name to index 
df1["new name"] = ["This", "is", "the", "new", "index"]
df1.set_index("new name", inplace = True)
df1

              col1      col2      col3      col4      col5
new name
This      0.732208  0.355399  0.195054  0.835518  0.491631
is        0.577719  0.453597  0.727921  0.864443 -0.640731
the       0.883460  0.292515  0.031291  0.652371  0.295773
new       0.707476  0.071373  0.105123  0.994128  1.080614
index     0.553048  0.559555  0.316286  0.041482  0.844003