#### Pandas support chaining operation

In [5]:
import pandas as pd
df = pd.read_csv("mall_customer.csv")

In [6]:
## select query

''' select * from customer'''
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [8]:
## LIMIT

''' select * from customer limit 7'''

df.head(7)

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40
5           6  Female   22                  17                      76
6           7  Female   35                  18                       6

In [14]:
## SELECT ... WHERE... (Single columns)

''' select Annual Income from customer where Age > 20'''

df[df["Age"] > 20] [["Annual Income (k$)"]]

     Annual Income (k$)
1                    15
3                    16
4                    17
5                    17
6                    18
..                  ...
195                 120
196                 126
197                 126
198                 137
199                 137

[183 rows x 1 columns]

In [15]:
## SELECT ... WHERE...( Multiple Columns)

''' select Annual Income, Gender, Age from customer where Age > 20'''

df[df["Age"] > 20] [["Annual Income (k$)", "Gender", "Age"]]

     Annual Income (k$)  Gender  Age
1                    15    Male   21
3                    16  Female   23
4                    17  Female   31
5                    17  Female   22
6                    18  Female   35
..                  ...     ...  ...
195                 120  Female   35
196                 126  Female   45
197                 126    Male   32
198                 137    Male   32
199                 137    Male   30

[183 rows x 3 columns]

In [16]:
## SELECT ... WHERE...( All)

''' select * from customer where Age > 20'''

df[df["Age"] > 20]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
1             2    Male   21                  15                      81
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[183 rows x 5 columns]

In [20]:
## Mutiple condition

'''SELECT * FROM customers WHERE Annual_Income_K_Dollars = 16 AND Spending_Score_1_to_100 = 6'''

df[(df["Gender"] == "Male") & (df["Age"] > 20)].head(5)

    CustomerID Gender  Age  Annual Income (k$)  Spending Score (1-100)
1            2   Male   21                  15                      81
8            9   Male   64                  19                       3
10          11   Male   67                  19                      14
14          15   Male   37                  20                      13
15          16   Male   22                  20                      79

In [21]:
##### AGGREGATE

In [28]:
'''SELECT mean(Age), max(Age), min(Age) FROM customers'''

df.agg({
    "Age": ["mean", "sum"],
    "Spending Score (1-100)" : ["max", "mean"]   
})

          Age  Spending Score (1-100)
max       NaN                    99.0
mean    38.85                    50.2
sum   7770.00                     NaN

In [29]:
#### DISTINCT

'''SELECT DISTINCT Annual_Income_K_Dollars FROM customers'''

df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [31]:
## ORDER BY (ASCENDING)
'''SELECT * FROM customers WHERE Gender = "Female" ORDER BY Spending Score (1-100)'''

df[df["Gender"] == "Female"].sort_values("Spending Score (1-100)")

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
140         141  Female   57                  75                       5
22           23  Female   46                  25                       5
2             3  Female   20                  16                       6
6             7  Female   35                  18                       6
136         137  Female   44                  73                       7
..          ...     ...  ...                 ...                     ...
163         164  Female   31                  81                      93
7             8  Female   23                  18                      94
167         168  Female   33                  86                      95
19           20  Female   35                  23                      98
11           12  Female   35                  19                      99

[112 rows x 5 columns]

In [53]:

#SQL Statement (Filtering on Genre called Female & Ordering By Spending_Score_1_to_100 in DESCENDING order)
'''SELECT * FROM customers WHERE Gender = "Female" ORDER BY Spending Score (1-100) DESC'''

df.groupby(['Gender', 'Age']).size().to_frame('Count').reset_index().sort_values('Age', ascending = False)

    Gender  Age  Count
86    Male   70      2
85    Male   69      1
42  Female   68      2
84    Male   68      1
83    Male   67      3
..     ...  ...    ...
2   Female   20      2
1   Female   19      2
44    Male   19      6
0   Female   18      1
43    Male   18      3

[87 rows x 3 columns]

In [37]:
## GROUPBY count
'''SELECT Genre, Age, count(*) FROM customers GROUPBY Genre, Age'''

df.groupby(["Gender", "Age"]).size()

Gender  Age
Female  18     1
        19     2
        20     2
        21     4
        22     2
              ..
Male    66     1
        67     3
        68     1
        69     1
        70     2
Length: 87, dtype: int64

In [42]:
#Formatting above
df.groupby(["Gender", "Age"]).size().to_frame("Count").reset_index()

    Gender  Age  Count
0   Female   18      1
1   Female   19      2
2   Female   20      2
3   Female   21      4
4   Female   22      2
..     ...  ...    ...
82    Male   66      1
83    Male   67      3
84    Male   68      1
85    Male   69      1
86    Male   70      2

[87 rows x 3 columns]

In [54]:
'''SELECT Genre, Age, count(*) FROM customers GROUPBY Genre, Age ORDER BY Age DESC'''

df.groupby(["Gender", "Age"]).size().to_frame("Count").reset_index().sort_values("Age", ascending = False)

    Gender  Age  Count
86    Male   70      2
85    Male   69      1
42  Female   68      2
84    Male   68      1
83    Male   67      3
..     ...  ...    ...
2   Female   20      2
1   Female   19      2
44    Male   19      6
0   Female   18      1
43    Male   18      3

[87 rows x 3 columns]

In [55]:
## HAVING

In [58]:
## IN STATEMENT
'''SELECT * FROM customers WHERE Age IN (20, 30, 40)'''

#Pandas Equivalant
# customers[customers.Age.isin([20,30,40])]

df[df['Age'].isin([20,30,40])]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
2             3  Female   20                  16                       6
9            10  Female   30                  19                      72
17           18    Male   20                  21                      66
28           29  Female   40                  29                      31
37           38  Female   30                  34                      73
39           40  Female   20                  37                      75
77           78    Male   40                  54                      48
93           94  Female   40                  60                      40
99          100    Male   20                  61                      49
122         123  Female   40                  69                      58
127         128    Male   40                  71                      95
134         135    Male   20                  73                       5
157         158  Female   30                  78                      78
159         160  Female   30                  78                      73
170         171    Male   40                  87                      13
175         176  Female   30                  88                      86
185         186    Male   30                  99                      97
199         200    Male   30                 137                      83

In [59]:
## NOT IN STATEMENT
'''SELECT * FROM customers WHERE Age IN (20, 30, 40)'''

#Pandas Equivalant
# customers[customers.Age.isin([20,30,40])]

df[~df['Age'].isin([20,30,40])]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
..          ...     ...  ...                 ...                     ...
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18

[182 rows x 5 columns]

In [60]:
#SQL Statement (Identify Top 10 records)
'''SELECT * FROM customers ORDER BY Spending_Score_1_to_100 DESC LIMIT 10'''

#Pandas Equivalant
df.nlargest(10, columns='Spending Score (1-100)')

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
145         146    Male   28                  77                      97
185         186    Male   30                  99                      97
127         128    Male   40                  71                      95
167         168  Female   33                  86                      95
7             8  Female   23                  18                      94
141         142    Male   32                  75                      93
163         164  Female   31                  81                      93
33           34    Male   18                  33                      92

In [61]:
## Above can also be done in this way

df.sort_values("Spending Score (1-100)", ascending = False).head(10)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
145         146    Male   28                  77                      97
185         186    Male   30                  99                      97
127         128    Male   40                  71                      95
167         168  Female   33                  86                      95
7             8  Female   23                  18                      94
141         142    Male   32                  75                      93
163         164  Female   31                  81                      93
41           42    Male   24                  38                      92

In [62]:
#SQL Statement (Identify Next Top 10 records)
'''SELECT * FROM customers ORDER BY Spending_Score_1_to_100 DESC LIMIT 10 OFFSET 10'''

#Pandas Equivalant
df.nlargest(20, columns='Spending Score (1-100)').tail(10)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
41           42    Male   24                  38                      92
173         174    Male   36                  87                      92
123         124    Male   39                  69                      91
193         194  Female   38                 113                      91
149         150    Male   34                  78                      90
179         180    Male   35                  93                      90
155         156  Female   27                  78                      89
135         136  Female   29                  73                      88
151         152    Male   39                  78                      88
183         184  Female   29                  98                      88

In [64]:

#SQL Statement (Insert a new record in the table)
'''INSERT INTO customers VALUES(401, 'Male', 50, 30, 20) '''

#Pandas Equivalant
df = df.append({'CustomerID':401, 'Gender':'Male', 'Age':50, 'Annual Income (k$)':30, 'Spending Score (1-100)':20}, ignore_index=True)

df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100) Genre
0             1    Male   19                  15                      39   NaN
1             2    Male   21                  15                      81   NaN
2             3  Female   20                  16                       6   NaN
3             4  Female   23                  16                      77   NaN
4             5  Female   31                  17                      40   NaN
..          ...     ...  ...                 ...                     ...   ...
197         198    Male   32                 126                      74   NaN
198         199    Male   32                 137                      18   NaN
199         200    Male   30                 137                      83   NaN
200         401     NaN   50                  30                      20  Male
201         401    Male   50                  30                      20   NaN

[202 rows x 6 columns]

In [70]:
#SQL Statement (Update an existing record in the table)
'''UPDATE customers SET Spending_Score_1_to_100 = 7 WHERE Spending_Score_1_to_100 = 6'''

#Pandas Equivalant
df[df['Spending Score (1-100)'] == 81] = 7

df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100) Genre
0             1    Male   19                  15                      39   NaN
1             7       7    7                   7                       7     7
2             7       7    7                   7                       7     7
3             4  Female   23                  16                      77   NaN
4             5  Female   31                  17                      40   NaN
..          ...     ...  ...                 ...                     ...   ...
197         198    Male   32                 126                      74   NaN
198         199    Male   32                 137                      18   NaN
199         200    Male   30                 137                      83   NaN
200         401     NaN   50                  30                      20  Male
201         401    Male   50                  30                      20   NaN

[202 rows x 6 columns]

In [86]:
#SQL Statement (Delete an existing record in the table)
'''DELETE FROM customers WHERE Spending_Score_1_to_100 = 7'''

#Pandas Equivalant

df = df.drop(df[df["Age"] == 7].index)

#df[df["Age"] == 19].index            ## gives rows with true conditions
df.iloc[61]

CustomerID                  66
Gender                    Male
Age                         18
Annual Income (k$)          48
Spending Score (1-100)      59
Genre                      NaN
Name: 65, dtype: object